#!/usr/bin/python3
"""A script to find the smallest divisor of integers from a file."""


import sys
import time


def find_divisor(INT=0):
    """Function to find the smallest divisor of an integer.
    Args:
        INT: integer input
    """
    for  x in range(2, INT):
        if INT % x == 0:
            return x, INT // x
    return None


if __name__ == "__main__":
    """Main function to find divisors."""

    start = time.time()

    # Check if the correct number of arguments are provided
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    try:
        # Open the file provided as an argument in read mode
        with open(sys.argv[1], 'r') as file:  # Read each line in the file

            for line in file:
                INT = int(line)     # Convert the line to an integer
                _div = find_divisor(INT)    # Find the smallest divisor of the integer
                print("{}={}*{}".format(INT, _div[1], _div[0]))    # Print the result
    except FileNotFoundError:
        sys.exit(2)

    if time.time() - start > 5:
        print("Time Limit Exceeded")
        sys.exit(3)
